version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD # value will be via "docker-compose up" call
  redis:
    image: "redis:latest"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # avoids that inside the container, this folder is overridden
      - ./server:/app     # all accessed file will be retrieved from "./server" folder